# 3. PyTorch Basics - Practice on Tensor Objects (Solution)

### About this notebook

This notebook was used in the 50.039 Deep Learning course at the Singapore University of Technology and Design.

**Author:** Matthieu DE MARI (matthieu_demari@sutd.edu.sg)

**Version:** 1.0 (22/06/2023)

**Requirements:**
- Torch (tested on v2.0.1+cu118)

### Imports and CUDA

In [1]:
# Torch
import torch

In [2]:
# Use GPU if available, else use CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda


### Question 1

Consider the tensor A below.

In [3]:
# Generating a random tensor, using seed for reproducibility
torch.manual_seed(17)
A = torch.rand(4, 6)
# This should print
# tensor([[4.3424e-01, 5.3511e-01, 8.3021e-01, 1.2386e-01, 2.9321e-02, 5.4940e-01],
#        [3.8249e-01, 5.4626e-01, 4.6828e-01, 1.7153e-02, 2.1382e-02, 3.6643e-01],
#        [2.0535e-01, 1.9226e-01, 3.5434e-01, 2.1795e-01, 1.0574e-04, 1.4056e-01],
#        [6.0028e-01, 5.6578e-01, 9.4895e-02, 9.6953e-02, 3.7144e-01, 2.6844e-02]])
print(A)

tensor([[4.3424e-01, 5.3511e-01, 8.3021e-01, 1.2386e-01, 2.9321e-02, 5.4940e-01],
        [3.8249e-01, 5.4626e-01, 4.6828e-01, 1.7153e-02, 2.1382e-02, 3.6643e-01],
        [2.0535e-01, 1.9226e-01, 3.5434e-01, 2.1795e-01, 1.0574e-04, 1.4056e-01],
        [6.0028e-01, 5.6578e-01, 9.4895e-02, 9.6953e-02, 3.7144e-01, 2.6844e-02]])


In this activity, we will come up with our own manual implementation of the mean for this tensor A, averaging elements in each column. This is something that we could do using the built-in torch function mean(), as shown below.

In [4]:
print("Ground truth:", A.mean(dim = 0))

Ground truth: tensor([0.4056, 0.4599, 0.4369, 0.1140, 0.1056, 0.2708])


Let us try to come up with our own implementation for this function, using for loops, instead of the built-in torch functions.

In [5]:
# Question: write a function to calculate the empirical mean value of each column.
def emp_mean(A):
    # Create an empty 1D tensor with the size corresponding to the number of columns in A
    val = torch.empty(A.shape[1]) 
    # Iterate over columns using a for loop
    for i in range(A.shape[1]):
        column_sum = 0
        # Iterate over rows using a second for loop (sum and then divide by number of elements)
        for j in range(A.shape[0]):
            column_sum += A[j, i]
        val[i] = column_sum / A.shape[0]
    return val

In [6]:
# Testing your function
print("Your function:", emp_mean(A))
# Grunt truth
print("Ground truth:", A.mean(dim = 0))

Your function: tensor([0.4056, 0.4599, 0.4369, 0.1140, 0.1056, 0.2708])
Ground truth: tensor([0.4056, 0.4599, 0.4369, 0.1140, 0.1056, 0.2708])


### Question 2

Consider the tensor B below.

In [7]:
# Generating a random tensor, using seed for reproducibility
torch.manual_seed(17)
B = torch.randint(0, 10, (5, 5))
# This should print
# tensor([[9, 5, 1, 2, 0],
#        [9, 8, 3, 2, 5],
#        [2, 9, 2, 2, 1],
#        [3, 4, 9, 7, 2],
#        [6, 4, 3, 3, 2]])
print(B)

tensor([[9, 5, 1, 2, 0],
        [9, 8, 3, 2, 5],
        [2, 9, 2, 2, 1],
        [3, 4, 9, 7, 2],
        [6, 4, 3, 3, 2]])


In this activity, we would like to find the indices at which the tensor B has values greater than 5.

This can typically be done with a mask and the nonzero() built-in function, as shown below.

In [8]:
mask = B > 5
print("Mask:", mask)
indices = torch.nonzero(mask)
print("Ground truth:", indices)

Mask: tensor([[ True, False, False, False, False],
        [ True,  True, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True,  True, False],
        [ True, False, False, False, False]])
Ground truth: tensor([[0, 0],
        [1, 0],
        [1, 1],
        [2, 1],
        [3, 2],
        [3, 3],
        [4, 0]])


Let us try to come up with our own implementation for this function, using for loops, instead of the built-in torch functions.

In [9]:
# Question: write a function to find the indices of a tensor where the value is greater than 5.
def find_indices(B):
    # Store the indices as lists in a list first
    indices_list = []
    for i in range(B.shape[0]):
        for j in range(B.shape[1]):
            if B[i, j] > 5:
                indices_list.append([i, j])
    # Convert the list of indices into a tensor
    indices = torch.tensor(indices_list)  
    return indices

In [10]:
# Testing your function
print("Your function:", find_indices(B))
# Grunt truth
print("Ground truth:", torch.nonzero(B > 5))

Your function: tensor([[0, 0],
        [1, 0],
        [1, 1],
        [2, 1],
        [3, 2],
        [3, 3],
        [4, 0]])
Ground truth: tensor([[0, 0],
        [1, 0],
        [1, 1],
        [2, 1],
        [3, 2],
        [3, 3],
        [4, 0]])


### Question 3

Consider the tensors C and D below.

In [11]:
# Generating random tensors, using seed for reproducibility
torch.manual_seed(17)
C = torch.rand(3, 3)
D = torch.rand(3, 4)
# This should print
# tensor([[0.4342, 0.5351, 0.8302],
#        [0.1239, 0.0293, 0.5494],
#        [0.3825, 0.5463, 0.4683]])
print(C)
# This should print
# tensor([[1.7153e-02, 2.1382e-02, 3.6643e-01, 2.0535e-01],
#        [1.9226e-01, 3.5434e-01, 2.1795e-01, 1.0574e-04],
#        [1.4056e-01, 6.0028e-01, 5.6578e-01, 9.4895e-02]])
print(D)

tensor([[0.4342, 0.5351, 0.8302],
        [0.1239, 0.0293, 0.5494],
        [0.3825, 0.5463, 0.4683]])
tensor([[1.7153e-02, 2.1382e-02, 3.6643e-01, 2.0535e-01],
        [1.9226e-01, 3.5434e-01, 2.1795e-01, 1.0574e-04],
        [1.4056e-01, 6.0028e-01, 5.6578e-01, 9.4895e-02]])


In this activity, we would like to concatenate both C and D to produce a 3-by-6 tensor.

This can typically be done with built-in functions, as shown below.

In [12]:
# Concatenate one next to the other
concatenated = torch.cat((C, D), dim = 1)
print("Ground truth:", concatenated)

Ground truth: tensor([[4.3424e-01, 5.3511e-01, 8.3021e-01, 1.7153e-02, 2.1382e-02, 3.6643e-01,
         2.0535e-01],
        [1.2386e-01, 2.9321e-02, 5.4940e-01, 1.9226e-01, 3.5434e-01, 2.1795e-01,
         1.0574e-04],
        [3.8249e-01, 5.4626e-01, 4.6828e-01, 1.4056e-01, 6.0028e-01, 5.6578e-01,
         9.4895e-02]])


Let us try to come up with our own implementation for this function, using for loops, instead of the built-in torch functions.

In [13]:
# Question: concatenate both C and D, side by side, to produce a 3-by-6 tensor.
# We will not implement size checks to confirm that the concatenation is possible.
# Leaving this as an extra challenge for students.
def concatenate(C, D):
    # Initialize an empty tensor with the desired final shape
    reshaped = torch.empty(C.shape[0], C.shape[1] + D.shape[1])

    # Iterate over the rows
    for i in range(C.shape[0]):
        # Iterate over the columns
        for j in range(C.shape[1] + D.shape[1]):
            if j < C.shape[1]:
                reshaped[i, j] = C[i, j]
            else:
                reshaped[i, j] = D[i, j - C.shape[1]]
    return reshaped

In [14]:
# Testing your function
print("Your function:", concatenate(C, D))
# Grunt truth
print("Ground truth:", torch.cat((C, D), dim = 1))

Your function: tensor([[4.3424e-01, 5.3511e-01, 8.3021e-01, 1.7153e-02, 2.1382e-02, 3.6643e-01,
         2.0535e-01],
        [1.2386e-01, 2.9321e-02, 5.4940e-01, 1.9226e-01, 3.5434e-01, 2.1795e-01,
         1.0574e-04],
        [3.8249e-01, 5.4626e-01, 4.6828e-01, 1.4056e-01, 6.0028e-01, 5.6578e-01,
         9.4895e-02]])
Ground truth: tensor([[4.3424e-01, 5.3511e-01, 8.3021e-01, 1.7153e-02, 2.1382e-02, 3.6643e-01,
         2.0535e-01],
        [1.2386e-01, 2.9321e-02, 5.4940e-01, 1.9226e-01, 3.5434e-01, 2.1795e-01,
         1.0574e-04],
        [3.8249e-01, 5.4626e-01, 4.6828e-01, 1.4056e-01, 6.0028e-01, 5.6578e-01,
         9.4895e-02]])


### Additional questions (answers not provided).

In order to practice your PyTorch Tensor skills, you may try to manually implement your own version of typical algorithms we ran on lists/Numpy arrays in previous classes, using the basic operations on PyTorch tensors.
For instance, try writing algorithms:
- Finding the maximum, minimum, median values of a given tensor,
- Transposing a given 2D tensor,
- Sorting a given 1D tensor (using bubble sort, insertion sort, selection sort, quick sort, merge sort),
- Generating a 1D array containing the first K Fibonacci numbers with K given,
- Computing the determinant value of a 2D tensor, and its eigenvalues/eigenvectors,
- Etc

Later, you can check their performance times compared to their Numpy/PyTorch implementations when running them on both CPU and CUDA (if available).

In which scenarios is it slower to implement said functions and run them on GPU?

### What's next?

In the next notebook, we will investigate how to implement the backpropagation mechanism using the PyTorch framework, and eventually use it to train our model.